springdoc:
  api-docs:
    groups:
      enable: true
    path: "/api/serverless/v3/api-docs"
  swagger-ui:
    path: "/api/serverless/swagger-ui.html"
server:
  port: 8090
spring:
  application:
    name: "Serverless Workflow Diagram Rest API"